### ISSUE TITLE
Prisma + PlanetScale の導入

### ISSUE THREAD

**Issue by mtkdv** [mtkdv/FavoLink#42]
## Task lists
- [x] PlanetScaleで組織、データベースを作成。
- [x] main ブランチを production ブランチに昇格。
- [x] main ブランチから dev ブランチを派生。
- [x] dev ブランチとローカル開発環境を接続。
- [x] main ブランチの DATABASE_URL を Vercel の production 環境と preview 環境にセットする。
